### ISSUE TITLE
拼写错误

### ISSUE THREAD

**Issue by rinne1998** [kizuna-ai-egg/kizuna-ai-mb#1]
https://github.com/kizuna-ai-egg/kizuna-ai-mb/blob/main/src/main.py 第16行
> os.environ['USERN~~MA~~E'] = 'UNCLE-LV'   

应为
> os.environ['USERN**AM**E'] = 'UNCLE-LV'

**Comment by uncle-lv** [comment]
It doesn't work without admin permissions on Windows11. So I have removed it. If you want to get an environment variable on Windows11, please run it with admin permissions.
